name: YzdPasswordFree
version: 1.0
main: yzdpasswordfree.yzdpasswordfree.YzdPasswordFree
api-version: 1.16
commands:
  ypf:
    description: plugin main command
permissions:
  yzdpasswordfree.commands.reload:
    description: reload plugin
    default: op