name: YzdPasswordFree
version: 0.9-beta
main: yzdpasswordfree.yzdpasswordfree.YzdPasswordFree
api-version: 1.16
commands:
  tpf:
    description: plugin main command
  yzdpasswordfree:
    description: plugin main command
